### PR TITLE
Updates for conda

### PR DESCRIPTION
**Pull request by skanwal**

### CODE REVIEW

**Comment by skanwal** [comment]
**Note:**

Renamed R/Rmd files for branding

**Review by pdiakumis — APPROVED** [review]
Nice - I can work on setting up conda recipes in https://github.com/umccr/conda_recipes for the conda requirements. I guess some of those could also be on CRAN now so I could submit PRs to bioconda/conda-forge.

**Comment by skanwal** [comment]
> I can work on setting up conda recipes in https://github.com/umccr/conda_recipes for the conda requirements

Do you mean the ones in conda yaml file?

> I guess some of those could also be on CRAN now so I could submit PRs to bioconda/conda-forge.
Happy to help with that also. Will follow your space for updates.

**Comment by pdiakumis** [comment]
Yep, so: 

- `activedriverwgs` is on CRAN now so no need to host in our conda channel (should open a PR in conda-forge), same for `manhattanly` and `lares`.
- `dndscv` is only on GitHub so we should host it ourselves.
- `beepr`, `h2o`, `mailr`, `googlesheets4` are already in conda-forge.

I'll loop you in on one of the PRs so you can learn the process.

**Pull request merged**
