### PR TITLE
Initialise RNAsum Rpackage

### PR DESCRIPTION
**Pull request by skanwal**
**Related to https://github.com/umccr/RNAsum/issues/57**

- Mostly following the instructions from https://r-pkgs.org/index.html
  - [initialised](https://github.com/umccr/RNAsum/commit/d29de20908d3dfccdfc3605cc5f21b50206461ea) the package via create_package()
  - [created](https://github.com/umccr/RNAsum/commit/67e93db017e160e398e4ac33bac58e50583e80c6) `inst` directory with following subfolders
         - cli/ for RNAseq_report.R
         - rmd/ for RNAseq_report.Rmd
         - rawdata/ for copying over data from /RNAsum/data
         - [conda/recipe](https://github.com/umccr/RNAsum/commit/4ca74d5658687025ab0907162dd0401d80b05da1) for meta.yaml 
  - [written](https://github.com/umccr/RNAsum/commit/8882c1750310c271e6989c6f7aca772f56cdc8bd) first iteration of DESCRIPTION file

- [check() ](https://r-pkgs.org/whole-game.html?q=check()#check) is throwing warnings (no errors, so that's a relief at-least) for `rawdata/` 

```
Found the following non-portable file paths:
     RNAsum/data/test_data/stratus/test_sample_WTS/RNAsum/test_sample_WTS.results/InputDataPlots/counts_vs_transformed.html
     RNAsum/data/test_data/stratus/test_sample_WTS/RNAsum/test_sample_WTS.results/InputDataPlots/filtering.png
     RNAsum/data/test_data/stratus/test_sample_WTS/RNAsum/test_sample_WTS.results/InputDataPlots/library_size.html
     RNAsum/data/test_data/stratus/test_sample_WTS/RNAsum/test_sample_WTS.results/InputDataPlots/normalisation.png
....
storing paths of more than 100 bytes is not portable:
....
Tarballs are only required to store paths of up to 100 bytes and cannot
  store those of more than 256 bytes, with restrictions including to 100
  bytes for the final component.
  See section ‘Package structure’ in the ‘Writing R Extensions’ manual.
```
  
**Next step** is to resolve these warnings.

- Searching for the issue online, the only way to address this would be to update data paths and rewrite the code so it uses updated data directory structure (unless there exists a smarter solution?).

- clean-up top level files/directories to get rid of  

```
> checking top-level files ... NOTE
  Non-standard files/directories found at top level:
    ‘TCGA_projects_summary.md’ ‘buildspec.yml’ ‘conda’ ‘deploy’ ‘docs’
    ‘envm’ ‘fusions’ ‘img’ ‘install.sh’ ‘processing’
    ‘report_structure.md’ ‘rmd_files’ ‘workflow’ ‘workflow.md’
```

### CODE REVIEW

**Comment by pdiakumis** [comment]
This is looking terrific already Sehrish!
A couple quick comments for next steps and next-next steps:

- Add non-standard files/directories into the `.Rbuildignore` file for now, can clean up later.
- Instead of copying the data files, I'd _move_ them (instead of having them duplicated in two places). I think if you delete the old ones it would show up as a rename in this PR.
- Don't worry about the non-portable file paths for now, we can fix that when refactoring the Rmd report.
- Lock dependency versions in DESCRIPTION only for pkgs that are problematic (i.e. `rapportools`) (or better still we should get rid of that pkg altogether during the refactor).
- For conda we'll need a `build.sh` file as well, maybe look at <https://github.com/umccr/gpgr/blob/main/conda/recipe/build.sh> for how I also export the cli as a bin (not now, later).
- For conda we should also chuck all the dependencies from Jacek's channel to the umccr channel (not now, later).
- We'll need to run, say, 5 'validation' samples through RNAsum in its current form and keep the results as a baseline so that we can be sure we haven't messed anything major up functionality-wise. 
  - We can create some small comparison utility functions woof-style too (not now, later).

**Comment by alexiswl** [comment]
> Lock dependency versions in DESCRIPTION only for pkgs that are problematic (i.e. rapportools) (or better still we should get rid of that pkg altogether during the refactor).

Yes to getting rid of that package! 

I think a general shift towards `::` notation might also help (we don't know which functions rapportools uses and using `package::function` notation definitely helps that.  

It also raises the issue that by not locking dependency versions, we do run the risk of introducing more issues like this and it does this is potentially a problem for running RNASum for production samples.  

Lets say the rapportools 1.1 bug didn't result in a failure but a success that we only discovered three months after its release into the production stage.  If we don't lock down the dependencies it might be quite difficult to tell which versions of RNASum were affected by this. If any of the docker containers for any of those versions needed to be rebuilt, we may also not know which samples might have been affected for a given RNASum version. 

For running RNASum in production, we want to know which dependency versions are being used for each RNASum release. If a container is rebuilt for any reason, it should also use the same dependency versions as the previous container. When updating RNASum versions, we'd also want to be able to see what dependencies have also been upgraded. 

This doesn't have to be in the conda lock file or the DESCRIPTION R file either, we could just wrap the installation of the RNASum package into renv via a Dockerfile and use a similar logic to what we do currently for new releases.

**Comment by pdiakumis** [comment]
> I think a general shift towards :: notation might also help

Yep, that will happen during the refactor down the road. Basically the functions from the Rmd will be exported into a proper file structure under `R/`, with tests also enabled, and where `devtools::check` will flag missing `::` notation.

Re: dependencies, yep, we discussed we can lock those down via conda-lock or renv. One step at a time ;-)

**Review by pdiakumis — APPROVED** [review]
LGTM

**Comment by skanwal** [comment]
Re - control samples, we have reports on S3 (detail [here](https://trello.com/c/BGVeyvrw/504-organize-wts-control-samples?filter=member:sehrishkanwal2)).
We can also generate RNAsum reports on ICA. The data for control samples currently sit under `gds://development/validation_data/wts/`

**Pull request merged**
