### PR TITLE
Rmd refactor (part 3)

### PR DESCRIPTION
**Pull request by pdiakumis**
- Remove bcbio-related README sections
- Deprecate GRCh37; use GRCh38 throughout
- Mini SQL cleanup
- Use quotations for `dplyr::select` instead of `.data` because `tidyverse` have updated their functionality.

### CODE REVIEW

**Comment by pdiakumis** [comment]
@skanwal I'm still working on that bug we discussed, will push a bit later!

**Comment by skanwal** [comment]
Sounds good @pdiakumis - I'll wait for a ping.

**Comment by pdiakumis** [comment]
@skanwal this should be good to go now, sorry for the delay. Most of the files have minor changes due to quoting variables, and you can ignore the files under `tests/testthat`.

**Review by skanwal — APPROVED** [review]
Thanks. As discussed, I'll test these changes with `rnasum-rpackage` branch.

**Pull request merged**
