### PR TITLE
Docker Buildx GH Actions update

### PR DESCRIPTION
**Pull request by alexiswl**
* Updated ::set-output syntax to $GITHUB_OUTPUT syntax
* Update docker/* actions to latest versions
  * setup-qemu-action: v1 -> v2
  * setup-buildx-action: v1 -> v2
  * login-action: v1 -> v2
  * build-push-action: v2 -> v4
* Set provenance to false to prevent creation of attestation manifest

Fixes https://github.com/umccr/RNAsum/issues/98

## TODO 
- [x] waiting on successful completion of https://github.com/umccr/RNAsum/actions/runs/5051509266
- [x] Checked out docker image 0.4.7-dev https://github.com/umccr/RNAsum/pkgs/container/rnasum/95313364?tag=0.4.7-dev

### CODE REVIEW

**Review by pdiakumis — APPROVED** [review]
Thanks for doing that Alexis - is 2.5hrs normal for the Docker build or just due to Bioconductor network issues?

**Comment by alexiswl** [comment]
> Thanks for doing that Alexis - is 2.5hrs normal for the Docker build or just due to Bioconductor network issues?

Probably not normal, is it network issues or is 3.14 no longer available? This happened on the build yesterday and then again today? https://github.com/umccr/RNAsum/issues/100

**Comment by pdiakumis** [comment]
Hm okay, a bit weird, let's just go with this for now (I guess the build succeeded in the end, right?)
We've had sort of similar issues when using bioconda for the bioconductor data pkgs.

**Comment by pdiakumis** [comment]
@alexiswl re: #100 (you got the century there!) I wouldn't spend too much time optimising/debugging the Dockerfile setup; we will probably transition to managing everything via conda (conda-locks) end of next month. If the Bioconductor archive fallback worked, I'd leave it at that for now.
We can add renv support too for local dev after that.

In my experience with PCGR's pure conda Docker setup it takes ~30min to build two pretty 'heavy' conda envs (pcgr + pcgrr) for OSX and Linux (and not in parallel either), _and_ generate a pkgdown doc website _and_ build the image, so I think we can save quite a bit of time compared to that normal ~1.5hrs build time we're currently getting.

**Review by skanwal — APPROVED** [review]
Thanks @alexiswl for looking into this.

**Comment by alexiswl** [comment]
Done, repushed the 0.4.7 tag to master so should be released in the next couple of house

**Pull request merged**
